export const en = {
  send: 'Send',
  end: 'End',
  confirm: 'Confirm',
  continue: 'Continue',
  allow: 'Allow',
  cancel: 'Cancel',
  apply: 'Apply',
  reject: 'Reject',
  accept: 'Accept',
  accepted: 'Accepted',
  know: 'I got it',
  submit: 'Submit',
  refresh: 'Refresh',
  update: 'Update',
  yes: 'Yes',
  no: 'No',
  edit: 'Edit',
  loading: 'Loading…',
  admin: 'Host',
  member: 'Member',
  member_list: 'Attendess list',
  search_member: 'Search attendess',
  suspend: 'Suspend',
  me: 'Me',
  host: 'Host',
  view_lecturer: 'View lecturer',
  view_tile: 'View tile',
  language: {
    zh: 'Chinese',
    en: 'English',
    select: 'Language select',
  },
  about: {
    title: 'About',
    check_upgrade: 'Check upgrade',
    register_account: 'Sign up Agora.io',
    view_document: 'View document',
    version_tips_all:
      'Version:{version}\nRTC SDK Version:{rtcVersion}, RTM SDK Version:{rtmVersion}\nWhiteBoard Version:{whiteBoardVersion}',
    product_disclaimer: 'Product disclaimer',
    policy: 'Privacy policy',
  },
  chat: {
    send: 'Send',
    input: 'Input content',
    no_mgs: 'No news yet',
  },
  net: {
    unavailable: 'No network available',
    request_error: 'Server request error: {error}',
    requests_expired: 'Requests expired',
    upload_success: 'Upload successfully',
    upload_failed: 'Failed to upload. Please check your network status.',
    request_sent: 'Request sent',
    sent_failed: 'Request sent failed',
    quality_poor: 'Your network quality is poor',
  },
  login: {
    signal: 'Signal',
    open_camera: 'Open camera',
    open_mic: 'Open mic',
    enter_setting: 'Setting before entering',
    enter: 'Enter',
    room_name: 'Room name',
    room_pwd: 'Room password',
    name: 'Name',
    role: 'Role',
    pwd_tips:
      '• When the room already exists, you need to enter the correct password\n• When the room does not exist, the password entered will become the password of this room\n• The room can be without password',
    limit_tip:
      'This is a testing product. Please refrain from using it commercially. The max duration per session is 45 minutes.',
    tip_room_name_empty: 'Please enter the room name',
    tip_room_name_over: 'Room name max length is 50 characters',
    tip_room_name_short: 'Room name min length is 3 characters',
    tip_room_pass_over: 'Password max length is 20 characters',
    tip_user_name_empty: 'Please enter the user name',
    tip_user_name_over: 'User name max length is 20 characters',
    tip_user_name_short: 'User name min length is 3 characters',
  },
  invite: {
    meeting_name: 'Meeting name:',
    meeting_pwd: 'Meeting password:',
    invited_by: 'Invited by:',
    web_link: 'Web link:',
    android_link: 'Android link:',
    ios_link: 'iOS link:',
    copy_meeting_info: 'Copy meeting information',
    copy_link: 'Copy Link',
    meeting_info_copy_success: 'Meeting information copy success',
  },
  whiteboard: {
    converting: 'Converting',
    title: 'White Board',
    enter: 'Enter WhiteBoard',
    end: 'Close whiteboard',
    join: 'Join editing',
    quit: 'Quit editing',
  },
  main: {
    router: 'Audio router',
    switcher: 'Switch camera',
    audio: 'Audio',
    video: 'Video',
    member: 'Member',
    chat: 'Chat',
    message: 'Message',
    notification: 'Notification',
    more: 'More',
    exit: 'Exit',
    user_mute: 'Mute',
    user_unmute: 'Unmute',
    user_close_video: 'Close video',
    user_open_video: 'Open video',
    user_set_as_host: 'Set as host',
    user_leave: 'leave',
    user_enter: 'enter',
    kick_out: 'Kick out',
    exit_title: 'Do you want to leave the room?',
    close_meeting: 'Close meeting',
    exit_meeting: 'Exit meeting',
    close_title: 'The meeting is over',
    rate: 'Please rate the conference call quality',
    removed_from_room: 'You have been removed from the room',
    screen_sharing: 'You are screen sharing',
    become_host: 'Become host',
    screen_share: 'Screen Share',
    whiteboard: 'White Board',
    record: 'Record',
    am: 'AM',
    pm: 'PM',
  },
  device: {
    camera: 'Camera',
    speaker: 'Speaker',
    microphone: 'Microphone',
    microphone_volume: 'Microphone Volume',
    speaker_volume: 'Speaker Volume',
  },
  signal: {
    delay: 'Delay',
    lose: 'Lose',
    status: 'Status',
    CPU: 'CPU',
  },
  error: {},
  toast: {
    start_recording: {
      title: 'Start Recording',
      body: 'Are you sure to start recording the classroom?',
      success: 'Recording successfully started',
    },
    stop_recording: {
      title: 'Stop Recording',
      body: 'Are you sure to stop recording the classroom?',
      success: 'Recording successfully stopped',
    },
    mute_all_mic: 'All members mic off',
    mute_all_cam: 'All members cam off',
    cam_permission_on: 'Permission needed to turn cam on',
    cam_permission_off: 'You can turn cam on freely',
    mic_permission_on: 'Permission needed to turn mic on',
    mic_permission_off: 'You can turn mic on freely',
    admin_turn_off_mic: 'Host turns off you mic',
    admin_turn_off_cam: 'Host turns off your cam',
    new_admin: '{name} is host',
    leave_room: '{name} left room',
    enter_room: '{name} entered the room',
    whiteboard_end: "{name}'s whiteboard ended",
    whiteboard_start: '{name} started whiteboard',
    whiteboard_join: '{name} joined whiteboard',
    screen_start: '{name} started screen share',
    screen_end: 'Screen share has ended',
    action_no_host: 'No host in the room.',
    action_mic_denied: 'Mic access is denied.',
    action_cam_denied: 'Camera access is denied.',
    action_toast_over_max_num:
      'Over {num} attendees, in/out notification muted.',
    action_notify_mute_always: 'In/out notification muted always.',
    board_ongoing: 'Whiteboard is ongoing',
    screen_ongoing: 'Screen share is ongoing',
    copy_success: 'Copy success',
    err_oss_host: 'Cannot acquire oss host',
  },
  scaffold: {
    search: 'Search',
    student_list: 'Student List',
    pencil: 'Pencil',
    laser_pointer: 'Laser pointer',
    straight: 'straight',
    circle: 'circle',
    rectangle: 'rectangle',
    selector: 'selector',
    eraser: 'eraser',
    color: 'color',
    blank_page: 'add page',
    move: 'move',
    follow: 'Follow',
    un_follow: 'UnFollow',
    screen_share: 'Screen Share',
    stop_screen_share: 'Stop Screen Share',
    cloud_storage: 'Cloud Storage',
    text: 'Text',
    tools: 'Tools',
    user_list: 'User List',
    delete: 'Delete',
  },

  cloud: {
    fileName: 'file name',
    size: 'size',
    progress: 'progress',
    updated_at: 'updated at',
    operation: 'operation',
    publicResources: 'Public Resources',
    personalResources: 'Personal Resources',
    downloadResources: 'Download Resources',
    upload: 'Upload',
    delete: 'Delete',
    download: 'Download',
    downloading: 'Download',
    pause: 'Pause',
    upload_success: 'Upload Success',
  },
  media: {
    camera: 'Camera',
    switch_camera: 'Switch Camera',
    microphone: 'Microphone',
    switch_microphone: 'Switch Microphone',
    microphone_volume: 'Microphone Volume',
    speaker: 'Speaker',
    switch_speaker: 'Switch Speaker',
    volume: 'Volume',
    adjust_volume: 'Adjust Volume',
    test_speaker: 'Test',
    camera_error:
      'Device exception, camera is unplugged or occupied and cannot be used!',
    microphone_error:
      'Device exception, microphone is unplugged or occupied and cannot be used!',
    mirror: 'mirror',
  },
  tool: {
    board_name: 'Whiteboard',
    selector: 'mouse selector',
    pencil: 'pencil',
    rectangle: 'rectangle',
    ellipse: 'ellipse',
    eraser: 'eraser',
    text: 'text',
    color_picker: 'color picker',
    add: 'add new page',
    upload: 'upload ',
    hand_tool: 'hand selector',
    extension_tool: 'extension tool',
    clear: 'clear',
    disk: 'disk',
    prev: 'back',
    next: 'forward',
    zoomIn: 'zoom in',
    zoomOut: 'zoom out',
    fullScreen: 'full screen',
    reduction: 'reduction',
    reset: 'center',
  },
  pretest: {
    title: 'Device Test',
    settingTitle: 'Device Setting',
    finishTest: 'Finish',
  },
  setting: {
    setting: 'Setting',
    media: 'Media',
    person: 'Person',
    avatar: 'Profile picture',
    camera: 'Camera',
    room: 'Room',
    about: 'About',
    mic: 'Mic',
    beauty: 'Beauty (Coming soon)',
    upload_log: 'Upload log',
    camera_approve: 'Permission needed to turn cam on',
    mic_approve: 'Permission needed to turn mic on',
    ai_noise: 'Ai audio noise reduction (Coming soon)',
    turn_off_notify: 'Turn off in/out notifications',
    log: 'Problems encountered upload log',
  },
  notify: {
    popup_apply_audio_title: '{name} applied to turn on the microphone',
    popup_apply_video_title: '{name} applied to turn on the camera',
    popup_accept_audio_apply_title:
      '{name} accepted your application to turn on the microphone',
    popup_reject_audio_apply_title:
      '{name} rejected your application to turn on the microphone',
    popup_accept_video_apply_title:
      '{name} accepted your application to turn on the camera',
    popup_reject_video_apply_title:
      '{name} rejected your application to turn on the camera',
    popup_apply_message: 'Do you agree to the application?',
    popup_request_to_turn_mic_on:
      'Request to turn mic on. Please prepare to speak in 20 seconds',
    popup_request_to_turn_cam_on:
      'Request to turn cam on. Please prepare to present in 20 seconds',
    popup_leave_with_screenshare_on:
      'You have ongoing screen share. Do you want to end it?',
    popup_leave_with_on: 'You have ongoing whiteboard. Do you want to end it?',
    popup_start_screen_share_tip:
      'Screen share will show everything on your screen. Please update your notification setting accordingly.',
    popup_start_sharing: 'Start sharing',
    popup_permission_needed_to_turn_mic_on: 'Permission needed to turn mic on',
    popup_permission_needed_to_turn_camera_on:
      'Permission needed to turn camera on',
    board_ongoing: 'Whiteboard is ongoing',
    screen_ongoing: 'Screen share is ongoing',
    host_max: 'This room already has max number of host',
    password_error: 'Password is incorrect',
    room_has_host:
      'There is already a host in the room, please contact the host to designate you as the host, up to 3 people at the same time as the host',
    board_max: 'The whiteboard participants has reached max number',
    user_is_host: 'User is already the host',
    room_max_member: 'The room is full!',
    room_max_broadcaster:
      'The number of broadcaster has reached max number  in the room!',
  },
  more: {
    invite: 'Invite',
    mute_all_camera: 'All attendees cam off',
    mute_all_mic: 'All attendees mic off',
    unmute_all: 'Unmute all',
    record: 'Record',
    open_board: 'Initiate whiteboard',
    close_board: 'End',
    join_board: 'Request editing',
    quit_board: 'Quit editing',
    open_screen: 'Screen share',
    close_screen: 'End screen share',
    mute_audio: 'Mute audio',
    unmute_audio: 'Unmute audio',
    close_video: 'Close video',
    open_video: 'Open video',
    set_host: 'Set as host',
    renounce_admin: 'Renounce host',
    become_admin: 'Become host',
    authorize_board: 'Authorize whiteboard authority',
    move_out: 'Move out',
    cancel_board: 'Withdraw whiteboard authority',
  },
  inout: {
    close_max_num:
      'Close the maximum number of participants in and out of notifications',
    always_on: 'Always on',
    always_off: 'Always off',
    num_above: '{num} above',
  },
  record: {
    copy_address: 'Copy address',
    record_success:
      'Cloud recording has been completed. Please copy the link and save it for 14 days',
    tip:
      'Only the host can initiate recording. Please apply to be the host first',
    is_not_owner:
      'You are not the initiator of this recording and cannot operate this recording',
    recording: 'Recording',
  },
  rating: {
    title: 'Rate',
    call_quality: 'Call Quality',
    function_completeness: 'Function Completeness',
    general_experience: 'General Experience',
    comment: 'Comment',
    comment_hint: 'Share your experience',
    star: '{num}Star',
  },
  disclaimer: {
    title: 'Product disclaimer',
    content: `Agora Live ("this product") is a product provided by Agora . Agora enjoys the copyright and ownership of this product. It is hereby granted free of charge to anyone who obtains a copy of this product and related documentation (hereinafter referred to as "software") to try the software without limitation, including but not limited to trial, copy, modify, merge, publish, distribute, but this product shall not be used For any commercial use, you may not sublicense and / or sell copies of the software.\n
    This product is provided "as is" without any express warranty, including but not limited to guarantees of suitability, suitability for specific purposes, and non-infringement. Whether it is due to any contract, infringement or other forms of conduct related to this product or the trial of this product or other methods, Agora will not be responsible for any claims, damages or other liabilities.\n
    You are free to choose whether to try the services provided by this product. If you download, install, or try the services provided in this product, it means that you trust the owner of the product, and Agora shall not be responsible for any form of loss or injury caused by yourself or others when you try the services provided in this product for any reason.`,
  },
  log: {
    title: 'Upload log',
    uploading: 'Uploading log',
    fail: 'Failed to upload again',
    repeat: 'Uploading, please do not click repeatedly',
    success: 'Upload succeeded',
  },
};
