export const zh = {
  end: '结束',
  confirm: '确认',
  continue: '继续',
  allow: '允许',
  cancel: '取消',
  apply: '申请',
  reject: '拒绝',
  accept: '同意',
  accepted: '已同意',
  know: '我知道了',
  submit: '提交',
  refresh: '刷新',
  yes: '是',
  no: '否',
  edit: '修改',
  loading: '加载中…',
  admin: '主持人',
  member: '成员',
  member_list: '与会者列表',
  search_member: '搜索与会者',
  suspend: '暂停',
  me: '我',
  host: '主持人',
  view_lecturer: '演讲者视图',
  view_tile: '平铺视图',
  language:{
    zh: '中文',
    en: '英语',
    select:'语言选择'
  },
  about: {
    title: '关于',
    check_upgrade: '检查更新',
    register_account: '注册声网账号',
    view_document: '查看文档',
    version_tips_all:
      '版本号：{version}\nRTC SDK版本号：{rtcVersion}， RTM SDK版本号：{rtmVersion}\n白板版本号：{whiteBoardVersion}',
    product_disclaimer: '免责声明',
    policy: '隐私政策',
  },
  chat: {
    send: '发送',
    input: '输入内容',
    no_mgs: '还没有消息',
  },
  net: {
    unavailable: '没有网络信号，请检查链接',
    request_error: '服务器请求失败：{error}',
    requests_expired: '请求已过期',
    upload_success: '上传成功',
    upload_failed: '上传失败，请检查您的网络状态',
    request_sent: '请求已发送',
    sent_failed: '请求发送失败',
    quality_poor: '您的网络质量差',
  },
  login: {
    signal: '信号',
    open_camera: '打开摄像头',
    open_mic: '打开麦克风',
    enter_setting: '入会前设置',
    enter: '加入',
    room_name: '房间名',
    room_pwd: '房间密码',
    name: '用户名',
    role: '角色',
    pwd_tips:
      '• 房间已存在时，需要输入正确的密码\n• 房间不存在时，输入的密码将成为这个房间的密码\n• 房间可以不设置密码',
    limit_tip: '本应用为测试产品，请勿商用。单次会议最长45分钟。',
    tip_room_name_empty: '请输入房间名',
    tip_room_name_over: '房间名最多为50个字符',
    tip_room_name_short: '房间名必须不小于3位',
    tip_room_pass_over: '密码最多为20个字符',
    tip_user_name_empty: '请输入用户名',
    tip_user_name_over: '用户名最多为20个字符',
    tip_user_name_short: '用户名必须不小于3位',
  },
  invite: {
    meeting_name: '会议名：',
    meeting_pwd: '会议密码：',
    invited_by: '邀请人：',
    web_link: '邀请链接：',
    android_link: 'Android下载链接：',
    ios_link: 'iOS下载链接：',
    copy_meeting_info: '复制会议信息',
    copy_link: '复制链接',
    clipboard: '成功保存到剪贴板',
    meeting_info_copy_success: '会议信息已复制',
  },
  setting: {
    setting: '设置',
    media: '音视频',
    person: '个人',
    avatar: '头像',
    camera: '摄像头',
    room: '房间',
    about: '关于',
    mic: '麦克风',
    beauty: '美颜（敬请期待）',
    upload_log: '上传日志',
    camera_approve: '开启摄像头需审批',
    mic_approve: '开启麦克风需审批',
    ai_noise: 'Ai降噪（敬请期待）',
    turn_off_notify: '关闭进出通知',
    log:"遇到问题上传日志"
  },
  whiteboard: {
    converting: '转换中',
    title: '白板',
    enter: '进入白板',
    end: '结束白板',
    join: '加入白板互动',
    quit: '放弃白板互动',
  },
  main: {
    router: '音频路由',
    switcher: '切换摄像头',
    audio: '音频',
    video: '视频',
    member: '成员',
    chat: '聊天',
    message: '消息',
    notification: '通知',
    more: '更多',
    exit: '离开',
    user_mute: '静音',
    user_unmute: '取消静音',
    user_close_video: '关闭视频',
    user_open_video: '打开视频',
    user_set_as_host: '设为主持人',
    user_leave: '用户离开',
    user_enter: '用户进入',
    kick_out: '移出房间',
    exit_title: '是否离开房间？',
    close_meeting: '结束会议',
    exit_meeting: '退出会议',
    close_title: '会议已结束',
    rate: '请您为会议通话质量打分',
    removed_from_room: '您已被移出房间',
    screen_sharing: '您正在屏幕共享',
    become_host: '成为主持人',
    screen_share: '屏幕共享',
    whiteboard: '白板',
    record: '录制',
    am: '上午',
    pm: '下午',
  },
  device: {
    camera: '摄像头',
    microphone: '麦克风',
    speaker: '扬声器',
    microphone_volume: '麦克风音量',
    speaker_volume: '扬声器音量',
  },
  signal: {
    delay: '网络延迟',
    lose: '丢包率',
    status: '网络状态',
    CPU: 'CPU',
  },
  error: {},
  toast: {
    start_recording: {
      title: '录制提示',
      body: '你确定要开始录制吗?',
      success: '录制开启成功',
    },
    stop_recording: {
      title: '停止录制',
      body: '你确定要停止录制吗?',
      success: '录制停止成功',
    },
    mute_all_mic: '关闭全员麦克风',
    mute_all_cam: '关闭全员摄像头',
    cam_permission_on: '开启摄像头需要主持人批准',
    cam_permission_off: '可以自由打开摄像头',
    mic_permission_on: '开启麦克风需要主持人批准',
    mic_permission_off: '可以自由打开麦克风',
    admin_turn_off_mic: '主持人关闭了您的麦克风',
    admin_turn_off_cam: '主持人关闭了您的摄像头',
    new_admin: '{name}成为主持人',
    leave_room: '{name}离开房间',
    enter_room: '{name}进入房间',
    whiteboard_end: '{name}的白板已结束',
    whiteboard_start: '{name}开始白板分享',
    whiteboard_join: '{name}加入白板互动',
    screen_start: '{name}开始屏幕共享',
    screen_end: '屏幕分享已结束',
    action_no_host: '房间内没有主持人。',
    action_mic_denied: '麦克风未授权。',
    action_cam_denied: '摄像头未授权。',
    action_toast_over_max_num: '超过{num}人，成员进出通知关闭。',
    action_notify_mute_always: '所有成员进出通知都已关闭',
    board_ongoing: '白板分享正在进行中',
    screen_ongoing: '屏幕分享正在进行中',
    host_max: '该房间管理员数量已经达到最大值',
    password_error: '密码不正确',
    room_has_host:
      '房间内已经有主持人，请联系主持人指定您为主持人',
    board_max: '白板已达到最大人数',
    user_is_host: '用户已经是主持人',
    room_max_member: '房间内人数已达上限',
    room_max_broadcaster: '房间内已达到主播数上限',
    copy_success: '复制成功',
    err_oss_host: '无法获取到此AppID下面的OSS host',
  },
  scaffold: {
    search: '搜索',
    student_list: '学生列表',
    pencil: '画笔',
    laser_pointer: '激光笔',
    straight: '直线',
    circle: '圆圈',
    rectangle: '矩形',
    selector: '选择',
    eraser: '橡皮擦',
    color: '颜色',
    blank_page: '新增一页',
    move: '移动工具',
    follow: '跟随模式',
    un_follow: '解除跟随',
    screen_share: '屏幕共享',
    stop_screen_share: '停止共享',
    cloud_storage: '云盘',
    text: '文本',
    tools: '工具栏',
    user_list: '用户列表',
    delete: '删除',
  },
  cloud: {
    fileName: '文件名字',
    size: '大小',
    progress: '进度条',
    operation: '操作',
    updated_at: '修改时间',
    publicResources: '公共资源',
    personalResources: '我的资源',
    downloadResources: '下载资源',
    upload: '上传',
    delete: '删除',
    download: '下载',
    downloading: '下载中',
    pause: '暂停',
    upload_success: '上传成功',
  },
  media: {
    camera: '摄像头',
    switch_camera: '切换摄像头',
    microphone: '麦克风',
    switch_microphone: '切换麦克风',
    microphone_volume: '麦克风音量',
    speaker: '扬声器',
    switch_speaker: '切换扬声器',
    volume: '音量',
    adjust_volume: '调整音量',
    test_speaker: '检测',
    camera_error: '摄像头被拔出或摄像头已占用，无法显示视频！',
    microphone_error: '麦克风被拔出或麦克风被占用，无法使用麦克风！',
    mirror: '镜像模式',
  },
  pretest: {
    title: '设备检测',
    settingTitle: '设备设置',
    finishTest: '完成',
  },
  tool: {
    board_name: '白板',
    selector: '鼠标选择器',
    pencil: '画笔',
    rectangle: '矩形',
    ellipse: '椭圆',
    eraser: '橡皮擦',
    text: '文字',
    color_picker: '调色板',
    add: '新增一页',
    upload: '上传',
    hand_tool: '手抓工具',
    extension_tool: '扩展',
    clear: '清除',
    disk: '云盘',
    prev: '后退',
    next: '前进',
    zoomIn: '放大',
    zoomOut: '缩小',
    fullScreen: '全屏',
    reduction: '还原',
    reset: '居中',
  },
  notify: {
    popup_apply_audio_title: '{name}申请打开麦克风',
    popup_apply_video_title: '{name}申请打开摄像头',
    popup_accept_audio_apply_title: '{name}同意了你打开麦克风的申请',
    popup_reject_audio_apply_title: '{name}拒绝了你打开麦克风的申请',
    popup_accept_video_apply_title: '{name}同意了你打开摄像头的申请',
    popup_reject_video_apply_title: '{name}拒绝了你打开摄像头的申请',
    popup_apply_message: '是否同意申请？',
    popup_request_to_turn_mic_on: '向主持人申请打开麦克风，请20秒内准备发言',
    popup_request_to_turn_cam_on: '向主持人申请打开摄像头，请20秒内准备亮相',
    popup_leave_with_screenshare_on: '您有正在进行的屏幕分享，需要结束分享吗？',
    popup_leave_with_whiteboard_on: '您有正在进行的白板分享，需要结束分享吗？',
    popup_start_screen_share_tip:
      '屏幕共享会展示您屏幕上所有的内容。请酌情调整您的通知设置',
    popup_start_sharing: '开始共享',
    popup_permission_needed_to_turn_mic_on: '开启麦克风需审批',
    popup_permission_needed_to_turn_camera_on: '开启摄像头需审批',
  },
  more: {
    invite: '邀请',
    mute_all_camera: '全员摄像头关闭',
    mute_all_mic: '全员麦克风关闭',
    unmute_all: '解除全体静音',
    record: '录制',
    open_board: '发起白板',
    close_board: '结束白板',
    join_board: '加入白板互动',
    quit_board: '放弃白板互动',
    open_screen: '屏幕共享',
    close_screen: '结束屏幕共享',
    mute_audio: '静音',
    unmute_audio: '解除静音',
    close_video: '关闭视频',
    open_video: '打开视频',
    set_host: '设为主持人',
    renounce_admin: '放弃主持人',
    become_admin: '成为主持人',
    authorize_board: '授予白板互动',
    move_out: '移出房间',
    cancel_board: '取消白板互动',
  },
  inout: {
    close_max_num: '关闭进出通知的与会者人数上限',
    always_on: '总是开启',
    always_off: '总是关闭',
    num_above: '{num}以上',
  },
  record: {
    copy_address: '复制地址',
    record_success: '云录制已完成请复制链接保存，录制保存14天',
    tip: '只有主持人可以发起录制，请先申请成为主持人',
    is_not_owner: '您不是本次录制发起者，无法操作本次录制',
    recording:"录制中"
  },
  rating: {
    title: '评分',
    call_quality: '音视频质量',
    function_completeness: '功能完整性',
    general_experience: '使用体验',
    comment: '撰写评论',
    comment_hint: '分享您的体验心得',
    star: '{num}星',
  },
  disclaimer: {
    title: '产品免责声明',
    content: `Agora Live（“本产品”）是由Agora提供的一款产品，Agora享有本产品的著作权和所有权。特此免费授予获得本产品和相关文档文件（以下简称“软件”）副本的任何人无限制地试用软件的权利，包括但不限于试用，复制，修改，合并，发布，分发，但本产品不得用于任何商业用途，不得再许可和/或出售该软件的副本。\n
    本产品按“现状”提供，没有任何形式的明示担保，包括但不限于对适配性、特定目的的适用性和非侵权性的担保。无论是由于与本产品或本产品的试用或其他方式有关的任何合同、侵权或其他形式的行为，Agora均不对任何索赔、损害或其他责任负责。\n
    您可以自由选择是否试用本产品提供的服务，如果您下载、安装、试用本产品中所提供的服务，即表明您信任该产品所有人，Agora对任何原因在试用本产品中提供的服务时可能对您自身或他人造成的任何形式的损失和伤害不承担任何责任。
    `,
  },
  log: {
    title: '上传日志',
    uploading: '上传日志中',
    fail: '失败，重新上传',
    repeat: '上传中，请勿重复点击',
    success: '上传成功',
  },
};
